export const actionTypes = {
  ADD_MOVIES: "ADD_MOVIES",
  ADD_TO_FAVOURITES: "ADD_TO_FAVOURITES",
  REMOVE_FROM_FAVOURITES: "REMOVE_FROM_FAVOURITES",
  SET_SHOW_FAVOURITES: "SET_SHOW_FAVOURITES",
  ADD_SEARCH_RESULT: "ADD_SEARCH_RESULT",
  ADD_MOVIE_TO_LIST: "ADD_MOVIE_TO_LIST",
  REMOVE_SEARCH_RESULT: "REMOVE_SEARCH_RESULT",
  ADD_FAVOURITES_ON_LOAD: "ADD_FAVOURITES_ON_LOAD",
};
